name: Publish VSCode Extension
on:
  release:
    types: [ published ]
  workflow_dispatch:
jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ toJSON(github.event.release) }}"
