name: Publish VSCode Extension
on:
  release:
    types: [ published ]
  workflow_dispatch:
jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - name: Setup node with cache
        uses: actions/setup-node@v3
        with:
          cache: npm
      - name: Download vsix file from release
        if: >-
          github.event.release && !github.event.release.draft && github.event.release.assets[0]
          && endsWith(github.event.release.assets[0].name, '.vsix')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo Downloadable at "${{ github.event.release.assets[0].browser_download_url }}"
          gh api -H "Accept: application/octet-stream" "${{ github.event.release.assets[0].url }}" \
          > "${{ github.event.release.assets[0].name }}"
      - name: List packaged files inside vsix
        run: unzip -l -vqq "${{ github.event.release.assets[0].name }}" | awk '{print $8}'
      - name: Publish to Open VSX Registry
        env:
          OVSX_PAT: ${{ secrets.OPENVSX_TOKEN }}
        if: ${{ env.OVSX_PAT != '' }}
        run: |
          npm i -g ovsx
          echo ovsx $(ovsx --version)
          echo ovsx publish "${{ github.event.release.assets[0].name }}"
      - name: Publish to VSCode Extension Marketplace
        env:
          VSCE_PAT: ${{ secrets.VS_MARKETPLACE_TOKEN }}
        if: ${{ env.VSCE_PAT != '' }}
        run: |
          npm i -g vsce
          echo vsce $(vsce --version)
          echo vsce publish -i "${{ github.event.release.assets[0].name }}"
